### ISSUE TITLE
[07/04/2024]: Convert JSQuarto to a CLI tool 

### ISSUE THREAD

**Issue by RealRichi3** [Open-Science-Community-Saudi-Arabia/JSquarto#37]
### Summary

To make it easier to use and setup, it'll be better to use JSquarto as a CLI tool, where use all it's functionalities with little setup process.

### What needs to be done?

- [x] *Add necessary command line arguments for all functionalities*
- [x] *Convert to an installable npm package*
- [x] *Test package on different OS (Windows, Mac, Linux)*
- [x] *Add detailed doc on usage (more like help guide withing the CLI)*

**Comment by BatoolMM** [comment]
hi @RealRichi3 - can I try to work on this?

**Comment by RealRichi3** [comment]
yea sure @BatoolMM

**Comment by RealRichi3** [comment]
See

#171
#172
#173
#174
#175
#178
